// Vehicle Life — 115-vehicle collection. Fixed images only; no visual customization.
// Existing activity unlock system remains compatible with this list.

const vehicleNames = [
  'Bicycle',
  'Activa',
  'Ntorq',
  'Pulsar',
  'Apache',
  'KTM Duke',
  'Royal Enfield',
  'Ninja',
  'Hayabusa',
  'Ducati',
  'BMW S1000RR',
  'WagonR',
  'Thar',
  'Scorpio',
  'Fortuner',
  'Audi',
  'BMW M4',
  'BMW M5',
  'Mercedes-AMG',
  'Lamborghini',
  'Ferrari',
  'McLaren',
  'Porsche',
  'Aston Martin',
  'Bugatti Chiron',
  'Koenigsegg Jesko',
  'Rimac Nevera',
  'Maruti Swift',
  'Honda City',
  'Hyundai Creta',
  'Tata Nexon',
  'Mahindra XUV700',
  'Mercedes-Benz C-Class',
  'BMW 3 Series',
  'Audi A6',
  'Lexus IS',
  'Range Rover Evoque',
  'Jeep Grand Cherokee',
  'Ford Ranger',
  'Toyota Hilux',
  'Land Rover Defender',
  'Volkswagen Golf GTI',
  'Subaru WRX',
  'Mazda RX-7',
  'Chevrolet Camaro',
  'Dodge Challenger',
  'Ford Mustang',
  'Tesla Model 3',
  'Audi R8',
  'Porsche 911',
  'Toyota GR Supra',
  'Nissan GT-R',
  'Honda Civic Type R',
  'Toyota GR86',
  'Mazda MX-5',
  'Subaru BRZ',
  'Mitsubishi Lancer Evolution',
  'Volkswagen Scirocco',
  'Renault Megane RS',
  'Mini Cooper JCW',
  'Alfa Romeo Giulia',
  'Volvo S60',
  'Jaguar F-Type',
  'Maserati Ghibli',
  'Genesis G80',
  'Cadillac CT5-V',
  'Lexus LC 500',
  'Infiniti Q60',
  'Acura NSX',
  'Chevrolet Corvette C8',
  'Nissan Z',
  'Lotus Emira',
  'Alpine A110',
  'Toyota GR Yaris',
  'Hyundai Elantra N',
  'Mercedes-AMG GT',
  'BMW Z4 M40i',
  'Audi RS5',
  'Audi RS7',
  'BMW M8',
  'Mercedes-AMG GT 63 S',
  'Porsche Cayman GT4',
  'Porsche Panamera Turbo',
  'Ferrari Roma',
  'Ferrari 488 GTB',
  'Ferrari SF90 Stradale',
  'Lamborghini Huracán',
  'Lamborghini Aventador',
  'Lamborghini Revuelto',
  'McLaren 720S',
  'McLaren 765LT',
  'Aston Martin Vantage',
  'Aston Martin DB12',
  'Bentley Continental GT',
  'Bentley Flying Spur',
  'Rolls-Royce Wraith',
  'Rolls-Royce Ghost',
  'Rolls-Royce Phantom',
  'Maserati MC20',
  'Pagani Huayra',
  'Pagani Utopia',
  'Bugatti Veyron',
  'Bugatti Bolide',
  'Koenigsegg Regera',
  'Koenigsegg Gemera',
  'Rimac Concept One',
  'Porsche 918 Spyder',
  'McLaren P1',
  'Ferrari LaFerrari',
  'Lamborghini Sian',
  'Mercedes-AMG One',
  'Aston Martin Valkyrie',
  'Gordon Murray T.50',
  'Lotus Evija',
  'Pininfarina Battista'
];

const emojis = ["🚲", "🏍️", "🏍️", "🏍️", "🏍️", "🏍️", "🏍️", "🏍️", "🏍️", "🏍️", "🏍️", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗"];
const categories = ["bike", "bike", "bike", "bike", "bike", "bike", "bike", "bike", "bike", "bike", "bike", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car", "car"];
const { validateProgression } = require('./vehicle-progression');

const progression = validateProgression(vehicleNames.length);
const vehicles = vehicleNames.map((name, i) => {
  const req = progression[i];
  return {
    id: i + 1,
    name,
    emoji: emojis[i],
    category: categories[i],
    vcHours: req.hours,
    messages: req.messages,
    image: `vehicle-${String(i + 1).padStart(2, '0')}.png`
  };
});

module.exports = { vehicles };
