// Vehicle Life — 115-vehicle collection. Fixed images only; no visual customization.
// Existing activity unlock system remains compatible with this list.

const vehicleNames = [
  'Bicycle',
  'Honda Activa',
  'TVS Ntorq',
  'Bajaj Pulsar',
  'TVS Apache',
  'Royal Enfield',
  'KTM Duke',
  'Kawasaki Ninja',
  'Suzuki Hayabusa',
  'Ducati',
  'BMW S1000RR',
  'Maruti Suzuki WagonR',
  'Maruti Suzuki Swift',
  'Tata Nexon',
  'Honda City',
  'Hyundai Creta',
  'Mahindra Thar',
  'Mahindra Scorpio',
  'Mahindra XUV700',
  'Toyota Fortuner',
  'Ford Ranger',
  'Toyota Hilux',
  'Land Rover Defender',
  'Jeep Grand Cherokee',
  'Range Rover Evoque',
  'Tesla Model 3',
  'Mercedes-Benz C-Class',
  'BMW 3 Series',
  'Audi A6',
  'Lexus IS',
  'Volkswagen Golf GTI',
  'Subaru WRX',
  'Mazda RX-7',
  'Ford Mustang',
  'Chevrolet Camaro',
  'Dodge Challenger',
  'Volvo S60',
  'Genesis G80',
  'Mazda MX-5',
  'Subaru BRZ',
  'Toyota GR Yaris',
  'Hyundai Elantra N',
  'Toyota GR86',
  'Volkswagen Scirocco',
  'Renault Megane RS',
  'Mini Cooper JCW',
  'Infiniti Q60',
  'Alfa Romeo Giulia',
  'Cadillac CT5-V',
  'Lexus LC 500',
  'Nissan Z',
  'Alpine A110',
  'Lotus Emira',
  'Honda Civic Type R',
  'Jaguar F-Type',
  'Mitsubishi Lancer Evolution',
  'Nissan GT-R',
  'Toyota GR Supra',
  'Porsche 911',
  'Acura NSX',
  'Chevrolet Corvette C8',
  'Lexus LC 500',
  'Ferrari 488 Pista',
  'Chevrolet Corvette',
  'Mercedes-AMG ONE',
  'Lamborghini Aventador SVJ',
  'Porsche 911 GT3 Touring',
  'McLaren Senna',
  'Mercedes-AMG GT',
  'BMW M8',
  'Mercedes-AMG GT 63 S',
  'Porsche Cayman GT4',
  'Porsche Panamera Turbo',
  'Maserati Ghibli',
  'Bentley Continental GT',
  'Bentley Flying Spur',
  'Rolls-Royce Wraith',
  'Rolls-Royce Ghost',
  'Rolls-Royce Phantom',
  'Maserati MC20',
  'Ferrari Roma',
  'Ferrari 488 GTB',
  'Ferrari SF90 Stradale',
  'Lamborghini Huracán',
  'Lamborghini Aventador',
  'Lamborghini Revuelto',
  'McLaren 720S',
  'McLaren 765LT',
  'Aston Martin Vantage',
  'Aston Martin DB12',
  'Audi R8',
  'Aston Martin DBS',
  'Porsche 918 Spyder',
  'McLaren',
  'Lamborghini',
  'Ferrari',
  'Bugatti Chiron',
  'Koenigsegg',
  'Hypercar',
  'Pagani Huayra',
  'Pagani Utopia',
  'Bugatti Veyron',
  'Bugatti Bolide',
  'Koenigsegg Regera',
  'Koenigsegg Gemera',
  'Rimac Concept One',
  'Porsche 918 Spyder',
  'McLaren P1',
  'Ferrari LaFerrari',
  'Lamborghini Sián',
  'Mercedes-AMG ONE',
  'Aston Martin Valkyrie',
  'Gordon Murray T.50',
  'Lotus Evija',
  'Pininfarina Battista'
];

const emojis = [
  "🚲",
  "🏍️", "🏍️", "🏍️", "🏍️", "🏍️",
  "🏍️", "🏍️", "🏍️", "🏍️", "🏍️",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗", "🚗",
  "🚗", "🚗", "🚗", "🚗", "🚗"
];

const categories = [
  "bike", "bike", "bike", "bike", "bike",
  "bike", "bike", "bike", "bike", "bike", "bike",
  "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car", "car", "car", "car", "car", "car", "car",
  "car", "car", "car", "car"
];

const { validateProgression } = require('./vehicle-progression');

const progression = validateProgression(vehicleNames.length);

const vehicles = vehicleNames.map((name, i) => {
  const req = progression[i];

  return {
    id: i + 1,
    name,
    emoji: emojis[i],
    category: categories[i],
    vcHours: req.hours,
    messages: req.messages,
    image: `vehicle-${String(i + 1).padStart(2, '0')}.png`
  };
});

module.exports = { vehicles };
